unit BazaForma;

interface

uses
  SysUtils, Classes, DB, ADODB, VKDBFDataSet;

type
  Tbaza = class(TDataModule)
    BD: TADOConnection;
    Reestr_sql: TADOQuery;
    Reestr_sqlId: TAutoIncField;
    Reestr_sqlDataReg: TDateTimeField;
    Reestr_sqlOper: TWideStringField;
    Reestr_sqlDatError: TDateTimeField;
    Reestr_sqlIndOps: TWideStringField;
    Reestr_sqlSoder: TMemoField;
    Reestr_sqlOtmetka: TIntegerField;
    Reestr_sqlDataOtmetka: TDateTimeField;
    Reestr_sqlSoderOtmetki: TMemoField;
    Reestr_sqlDokOtm: TWideStringField;
    Reestr_sqlFioOm: TWideStringField;
    Reestr_sqlPOSTINDEX: TWideStringField;
    Reestr_sqlOPSNAME: TWideStringField;
    Reestr_sqlOPSTYPE: TWideStringField;
    Reestr_sqlOPSSUBM: TWideStringField;
    Reestr_sqlREGION: TWideStringField;
    Reestr_sqlAUTONOM: TWideStringField;
    Reestr_sqlAREA: TWideStringField;
    Reestr_sqlCITY: TWideStringField;
    Reestr_sqlCITY_1: TWideStringField;
    Reestr_sqlACTDATE: TDateTimeField;
    Reestr_sqlINDEXOLD: TWideStringField;
    Reestr_sql_e: TDataSource;
    Gurnal: TADOTable;
    GurnalId: TAutoIncField;
    GurnalDataReg: TDateTimeField;
    GurnalOper: TWideStringField;
    GurnalDatError: TDateTimeField;
    GurnalIndOps: TWideStringField;
    GurnalSoder: TMemoField;
    GurnalOtmetka: TIntegerField;
    GurnalDataOtmetka: TDateTimeField;
    GurnalSoderOtmetki: TMemoField;
    GurnalDokOtm: TWideStringField;
    GurnalFioOm: TWideStringField;
    sql_ops: TADOQuery;
    sql_opsOpsname: TWideStringField;
    sql_Upd: TADOQuery;
    sql_akt: TADOQuery;
    sql_user: TADOQuery;
    sql_userID: TAutoIncField;
    sql_userBos: TWideStringField;
    sql_userBosDolgn: TWideStringField;
    sql_userUser1: TWideStringField;
    sql_userUser1Dolgn: TWideStringField;
    sql_userUser2: TWideStringField;
    sql_userUser2Dolgn: TWideStringField;
    sql_userUser3: TWideStringField;
    TabSetup: TADOTable;
    sql_userUser3Dolgn: TWideStringField;
    sql_userBoskomu: TWideStringField;
    sql_userUser1komu: TWideStringField;
    sql_userUser2Komu: TWideStringField;
    sql_userUser3Komu: TWideStringField;
    sql_userIndPoctamt: TWideStringField;
    TabSetupID: TAutoIncField;
    TabSetupBos: TWideStringField;
    TabSetupBosDolgn: TWideStringField;
    TabSetupUser1: TWideStringField;
    TabSetupUser1Dolgn: TWideStringField;
    TabSetupUser2: TWideStringField;
    TabSetupUser2Dolgn: TWideStringField;
    TabSetupUser3: TWideStringField;
    TabSetupUser3Dolgn: TWideStringField;
    TabSetupBoskomu: TWideStringField;
    TabSetupUser1komu: TWideStringField;
    TabSetupUser2Komu: TWideStringField;
    TabSetupUser3Komu: TWideStringField;
    TabSetupIndPoctamt: TWideStringField;
    DelGrn: TADOTable;
    DelGrnId: TAutoIncField;
    DelGrnDataReg: TDateTimeField;
    DelGrnOper: TWideStringField;
    DelGrnDatError: TDateTimeField;
    DelGrnIndOps: TWideStringField;
    DelGrnSoder: TMemoField;
    DelGrnOtmetka: TIntegerField;
    DelGrnDataOtmetka: TDateTimeField;
    DelGrnSoderOtmetki: TMemoField;
    DelGrnDokOtm: TWideStringField;
    DelGrnFioOm: TWideStringField;
    DelGrnIdZ: TIntegerField;
    Reestr_del_sql: TADOQuery;
    Reestr_del_sqlID: TAutoIncField;
    Reestr_del_sqlIdZ: TIntegerField;
    Reestr_del_sqlDataReg: TDateTimeField;
    Reestr_del_sqlOper: TWideStringField;
    Reestr_del_sqlDatError: TDateTimeField;
    Reestr_del_sqlIndOps: TWideStringField;
    Reestr_del_sqlSoder: TMemoField;
    Reestr_del_sqlOtmetka: TIntegerField;
    Reestr_del_sqlDataOtmetka: TDateTimeField;
    Reestr_del_sqlSoderOtmetki: TMemoField;
    Reestr_del_sqlDokOtm: TWideStringField;
    Reestr_del_sqlFioOm: TWideStringField;
    Reestr_del_sqlPOSTINDEX: TWideStringField;
    Reestr_del_sqlOPSNAME: TWideStringField;
    Reestr_del_sqlOPSTYPE: TWideStringField;
    Reestr_del_sqlOPSSUBM: TWideStringField;
    Reestr_del_sqlREGION: TWideStringField;
    Reestr_del_sqlAUTONOM: TWideStringField;
    Reestr_del_sqlAREA: TWideStringField;
    Reestr_del_sqlCITY: TWideStringField;
    Reestr_del_sqlCITY_1: TWideStringField;
    Reestr_del_sqlACTDATE: TDateTimeField;
    Reestr_del_sqlINDEXOLD: TWideStringField;
    Reestr_del_sel_e: TDataSource;
    sql_user_W: TADOQuery;
    sql_user_w_e: TDataSource;
    sql_user_WID: TIntegerField;
    sql_user_WNAMEUSER: TWideStringField;
    sql_user_WDATCREAT: TDateTimeField;
    sql_user_WDATIN: TDateTimeField;
    sql_user_WDATCLOS: TDateTimeField;
    sql_user_WTIPUSER: TIntegerField;
    sql_user_WSTATUS: TIntegerField;
    sql_doklad: TADOQuery;
    sql_dokladId: TAutoIncField;
    sql_dokladDataReg: TDateTimeField;
    sql_dokladOper: TWideStringField;
    sql_dokladDatError: TDateTimeField;
    sql_dokladIndOps: TWideStringField;
    sql_dokladSoder: TMemoField;
    sql_dokladOtmetka: TIntegerField;
    sql_dokladDataOtmetka: TDateTimeField;
    sql_dokladSoderOtmetki: TMemoField;
    sql_dokladDokOtm: TWideStringField;
    sql_dokladFioOm: TWideStringField;
    sql_dokladPOSTINDEX: TWideStringField;
    sql_dokladOPSNAME: TWideStringField;
    sql_dokladOPSTYPE: TWideStringField;
    sql_dokladOPSSUBM: TWideStringField;
    sql_dokladREGION: TWideStringField;
    sql_dokladAUTONOM: TWideStringField;
    sql_dokladAREA: TWideStringField;
    sql_dokladCITY: TWideStringField;
    sql_dokladCITY_1: TWideStringField;
    sql_dokladACTDATE: TDateTimeField;
    sql_dokladINDEXOLD: TWideStringField;
    Sql_Ops_Sprav: TADOQuery;
    Sql_Ops_Sprav_e: TDataSource;
    Sql_Ops_SpravPOSTINDEX: TWideStringField;
    Sql_Ops_SpravOPSNAME: TWideStringField;
    Sql_Ops_SpravOPSTYPE: TWideStringField;
    Sql_Ops_SpravOPSSUBM: TWideStringField;
    Sql_Ops_SpravREGION: TWideStringField;
    Sql_Ops_SpravAUTONOM: TWideStringField;
    Sql_Ops_SpravAREA: TWideStringField;
    Sql_Ops_SpravCITY: TWideStringField;
    Sql_Ops_SpravCITY_1: TWideStringField;
    Sql_Ops_SpravACTDATE: TDateTimeField;
    Sql_Ops_SpravINDEXOLD: TWideStringField;
    Sql_Ops_SpravMAIL: TWideStringField;
    Sql_Ops_SpravID: TAutoIncField;
    Sql_Ops_SpravPOSTIND: TWideStringField;
    sql_vip: TADOQuery;
    sql_vip_e: TDataSource;
    Vipiska: TADOTable;
    VipSoder: TADOTable;
    VipiskaID: TAutoIncField;
    VipiskaIndOps: TWideStringField;
    VipiskaUserCr: TWideStringField;
    sql_aktId: TAutoIncField;
    sql_aktDataReg: TDateTimeField;
    sql_aktOper: TWideStringField;
    sql_aktDatError: TDateTimeField;
    sql_aktIndOps: TWideStringField;
    sql_aktSoder: TMemoField;
    sql_aktOtmetka: TIntegerField;
    sql_aktDataOtmetka: TDateTimeField;
    sql_aktSoderOtmetki: TMemoField;
    sql_aktDokOtm: TWideStringField;
    sql_aktFioOm: TWideStringField;
    sql_aktPOSTINDEX: TWideStringField;
    sql_aktOPSNAME: TWideStringField;
    sql_aktOPSTYPE: TWideStringField;
    sql_aktOPSSUBM: TWideStringField;
    sql_aktREGION: TWideStringField;
    sql_aktAUTONOM: TWideStringField;
    sql_aktAREA: TWideStringField;
    sql_aktCITY: TWideStringField;
    sql_aktCITY_1: TWideStringField;
    sql_aktACTDATE: TDateTimeField;
    sql_aktINDEXOLD: TWideStringField;
    VipSoderID: TAutoIncField;
    VipSoderID_VIP: TIntegerField;
    VipSoderID_ZAP: TIntegerField;
    sql_vip_sod: TADOQuery;
    VipiskaPrn: TADOTable;
    VipiskaMail: TADOTable;
    sql_vip_sod_e: TDataSource;
    sql_vip_sodAId: TAutoIncField;
    sql_vip_sodID_VIP: TIntegerField;
    sql_vip_sodID_ZAP: TIntegerField;
    sql_vip_sodBId: TAutoIncField;
    sql_vip_sodDataReg: TDateTimeField;
    sql_vip_sodOper: TWideStringField;
    sql_vip_sodDatError: TDateTimeField;
    sql_vip_sodIndOps: TWideStringField;
    sql_vip_sodSoder: TMemoField;
    sql_vip_sodOtmetka: TIntegerField;
    sql_vip_sodDataOtmetka: TDateTimeField;
    sql_vip_sodSoderOtmetki: TMemoField;
    sql_vip_sodDokOtm: TWideStringField;
    sql_vip_sodFioOm: TWideStringField;
    VipiskaPrnID: TAutoIncField;
    VipiskaPrnID_VIP: TIntegerField;
    VipiskaPrnDAT_PRINT: TDateTimeField;
    sql_Vip_prn: TADOQuery;
    Sql_Vpi_Prn_e: TDataSource;
    sql_vipID: TAutoIncField;
    sql_vipIndOps: TWideStringField;
    sql_vipDTC: TDateTimeField;
    sql_vipUserCr: TWideStringField;
    sql_vipPOSTINDEX: TWideStringField;
    sql_vipOPSNAME: TWideStringField;
    sql_vipOPSTYPE: TWideStringField;
    sql_vipOPSSUBM: TWideStringField;
    sql_vipREGION: TWideStringField;
    sql_vipAUTONOM: TWideStringField;
    sql_vipAREA: TWideStringField;
    sql_vipCITY: TWideStringField;
    sql_vipCITY_1: TWideStringField;
    sql_vipACTDATE: TDateTimeField;
    sql_vipINDEXOLD: TWideStringField;
    sql_user_WMAIL: TWideStringField;
    sql_user_WLOG: TWideStringField;
    sql_user_WPAS: TWideStringField;
    sql_user_WSERV: TWideStringField;
    sql_user_Wport: TIntegerField;
    VipiskaMailID: TAutoIncField;
    VipiskaMailID_VIP: TIntegerField;
    VipiskaMailDAT_MAIL: TDateTimeField;
    Sql_Vip_MAIL: TADOQuery;
    SQL_VIP_MAIL_E: TDataSource;
    VipiskaDTC: TDateTimeField;
    Reestr_sqltiperror: TIntegerField;
    Reestr_sqlfioError: TWideStringField;
    Reestr_del_sqltiperror: TIntegerField;
    Reestr_del_sqlfioError: TWideStringField;
    Reestr_del_sqlTipFioError: TIntegerField;
    Reestr_sqlTipFioError: TIntegerField;
    DelGrntiperror: TIntegerField;
    DelGrnfioError: TWideStringField;
    DelGrnTipFioError: TIntegerField;
    Gurnaltiperror: TIntegerField;
    GurnalfioError: TWideStringField;
    GurnalTipFioError: TIntegerField;
    Sql_error: TADOQuery;
    Sql_errorId: TAutoIncField;
    Sql_errorNumError: TWideStringField;
    Sql_errorTextError: TWideStringField;
    ErorSprav: TADOTable;
    ErorSpravId: TAutoIncField;
    ErorSpravNumError: TWideStringField;
    ErorSpravTextError: TWideStringField;
    sql_error_e: TDataSource;
    sql_akte: TADOTable;
    sql_akteId: TAutoIncField;
    sql_akteDataReg: TDateTimeField;
    sql_akteOper: TWideStringField;
    sql_akteDatError: TDateTimeField;
    sql_akteIndOps: TWideStringField;
    sql_akteSoder: TMemoField;
    sql_akteOtmetka: TIntegerField;
    sql_akteDataOtmetka: TDateTimeField;
    sql_akteSoderOtmetki: TMemoField;
    sql_akteDokOtm: TWideStringField;
    sql_akteFioOm: TWideStringField;
    sql_aktetiperror: TIntegerField;
    sql_aktefioError: TWideStringField;
    sql_akteTipFioError: TIntegerField;
    sql_aktePOSTINDEX: TWideStringField;
    sql_akteOPSNAME: TWideStringField;
    sql_akteOPSTYPE: TWideStringField;
    sql_akteOPSSUBM: TWideStringField;
    sql_akteREGION: TWideStringField;
    sql_akteAUTONOM: TWideStringField;
    sql_akteAREA: TWideStringField;
    sql_akteCITY: TWideStringField;
    sql_akteCITY_1: TWideStringField;
    sql_akteACTDATE: TDateTimeField;
    sql_akteINDEXOLD: TWideStringField;
    TabSetupNamePodr: TWideStringField;
    TabSetupIndPodr: TWideStringField;
    TabSetupTipPodr: TIntegerField;
    sql_userNamePodr: TWideStringField;
    sql_userIndPodr: TWideStringField;
    sql_userTipPodr: TIntegerField;
    ImpSprav: TVKDBFNTX;
    Ops_sprav: TADOTable;
    Reestr_sqlProc: TIntegerField;
    Reestr_del_sqlProc: TIntegerField;
    GurnalProc: TIntegerField;
    sql_doklad_i: TADOQuery;
    sql_doklad_iid: TAutoIncField;
    sql_doklad_iDat1: TDateTimeField;
    sql_doklad_iDat2: TDateTimeField;
    sql_doklad_idatcr: TDateTimeField;
    Doklad: TADOTable;
    DokladId: TAutoIncField;
    DokladDat1: TDateTimeField;
    DokladDat2: TDateTimeField;
    DokladDatCr: TDateTimeField;
    DokladUserD: TWideStringField;
    sql_stat: TADOQuery;
    Reestr_sqlErrorNot: TIntegerField;
    Reestr_sqlDatMailVip: TDateTimeField;
    Reestr_sqlDatPrnVip: TDateTimeField;
    GurnalErrorNot: TIntegerField;
    GurnalDatMailVip: TDateTimeField;
    GurnalDatPrnVip: TDateTimeField;
    Reestr_del_sqlERRORNOT: TIntegerField;
    Reestr_del_sqlDATMAILVIP: TDateTimeField;
    Reestr_del_sqlDATPRNVIP: TDateTimeField;
    sql_Vip_prnID: TAutoIncField;
    sql_Vip_prnID_VIP: TIntegerField;
    sql_Vip_prnDAT_PRINT: TDateTimeField;
    Sql_Vip_MAILID: TAutoIncField;
    Sql_Vip_MAILID_VIP: TIntegerField;
    Sql_Vip_MAILDAT_MAIL: TDateTimeField;
    sql_stat_e: TDataSource;
    sql_stat_ops: TADOQuery;
    sql_stat_ops_e: TDataSource;
    sql_stat_oper: TADOQuery;
    sql_stat_oper_e: TDataSource;
    sql_sprav: TADOQuery;
    sql_exp: TADOQuery;
    procedure Reestr_sqlOtmetkaGetText(Sender: TField; var Text: String;
      DisplayText: Boolean);
    procedure sql_vip_sodOtmetkaGetText(Sender: TField; var Text: String;
      DisplayText: Boolean);
    procedure Reestr_sqltiperrorGetText(Sender: TField; var Text: String;
      DisplayText: Boolean);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  baza: Tbaza;

implementation

uses Glavn, Addforma, ReportForm, SetupForma, DokladForma, UserForma,
  OpsForma, MailForma;

{$R *.dfm}

procedure Tbaza.Reestr_sqlOtmetkaGetText(Sender: TField; var Text: String;
  DisplayText: Boolean);
begin
  if baza.Reestr_sql.RecordCount>0 then
    case baza.Reestr_sqlOtmetka.Value of
      0: text:='Зарегистр.';
      1: Text:='В работе';
      2: text:='Завершено';
    else
      text:='';
    end;
end;

procedure Tbaza.sql_vip_sodOtmetkaGetText(Sender: TField; var Text: String;
  DisplayText: Boolean);
begin
  if baza.sql_vip_sod.RecordCount=0 then exit;
     case baza.sql_vip_sodOtmetka.Value of
      0: text:='Зарегистр.';
      1: Text:='В работе';
      2: text:='Завершено';
    else
      text:='';
    end;
end;

procedure Tbaza.Reestr_sqltiperrorGetText(Sender: TField; var Text: String;
  DisplayText: Boolean);
begin
  if baza.Reestr_sql.RecordCount=0 then exit;
  if baza.Sql_error.Locate('ID',baza.Reestr_sqltiperror.Value,[]) then
    text:=baza.Sql_errorNumError.Value
  else
  text:='';
end;

end.
